In [1]:
import pandas as pd
import numpy as np

In [2]:
data={
    "names":["sai","sri","mani","valli"],
    "scores":[72,50,90,80]
}
df=pd.DataFrame(data)
print(df)

   names  scores
0    sai      72
1    sri      50
2   mani      90
3  valli      80

In [3]:
df=pd.read_csv(r"c:\DATA SCIENCE\Machine_Learning\Datasets\adultdata.csv")
df.head(10)

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
5,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
6,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
7,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
8,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
9,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K

In [4]:
data={
    "age":[25,30,35,40,45,50,15,12,26,34,15,62,45,15,26,32,62,32,51,32,62,15]
}
df=pd.DataFrame(data)
df[df["age"]>30]

    age
2    35
3    40
4    45
5    50
9    34
11   62
12   45
15   32
16   62
17   32
18   51
19   32
20   62

In [5]:
data={
    "score":[25,30,35,40,45,50,15,12,26,34,15,62,45,15,26,32,62,32,51,32,62,15]
}
df=pd.DataFrame(data)
print(df["score"].mean())
print(df["score"].median())
print(df["score"].std())

34.59090909090909
32.0
15.936358820870359

In [6]:
data={
    "score":[25,np.nan,35,40,45,50,15,12,26,34,15,62,45,15,26,32,62,32,51,32,62,15]
}
df=pd.DataFrame(data)
df.head()
df.isnull()
df["score"].fillna(df["score"].mean(),inplace=True)
df.head()
df.isnull().sum()

C:\Users\prasa\AppData\Local\Temp\ipykernel_7068\3481764687.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["score"].fillna(df["score"].mean(),inplace=True)

score    0
dtype: int64

In [7]:
data={
    "score":[25,np.nan,35,40,45,50,15,12,26,34,15,62,45,15,26,32,62,32,51,32,62,15]
}
df=pd.DataFrame(data)
df.head()
df.isnull()
df.dropna()
df

    score
0    25.0
1     NaN
2    35.0
3    40.0
4    45.0
5    50.0
6    15.0
7    12.0
8    26.0
9    34.0
10   15.0
11   62.0
12   45.0
13   15.0
14   26.0
15   32.0
16   62.0
17   32.0
18   51.0
19   32.0
20   62.0
21   15.0

In [11]:
data={
    "dept":["HR","IT","Finance","HR","IT","Finance"],
    "salary":[50000,60000,55000,52000,62000,58000]
}
df=pd.DataFrame(data)
print(df.groupby("dept")["salary"].mean())

dept
Finance    56500.0
HR         51000.0
IT         61000.0
Name: salary, dtype: float64

In [12]:
data={
    "salary":[50000,60000,55000,52000,62000,58000]
}
df=pd.DataFrame(data)
df.sort_values(by="salary",ascending=False)

   salary
4   62000
1   60000
5   58000
2   55000
3   52000
0   50000

In [13]:
data={
    "Score":[25,30,35,40,45,50,15,12,26,34,15,62,45,15,26,32,62,32,51,32,62,15],
    "bonus":[5,10,15,20,25,30,3,2,4,6,3,12,9,3,4,5,12,6,10,6,12,3]
}
df=pd.DataFrame(data)
print(df.head())
df["total"]=df["Score"]+df["bonus"]
df.head()

   Score  bonus
0     25      5
1     30     10
2     35     15
3     40     20
4     45     25

   Score  bonus  total
0     25      5     30
1     30     10     40
2     35     15     50
3     40     20     60
4     45     25     70

In [14]:
df["total"].to_numpy()

array([30, 40, 50, 60, 70, 80, 18, 14, 30, 40, 18, 74, 54, 18, 30, 37, 74,
       38, 61, 38, 74, 18])